server:
  port: ${PORT}
spring:
  cloud:
    gateway:
      routes:
        - id: members
          uri: ${MEMBER} # http://localhost:8070
          predicates:
            - Path=/api/v1/members/**
          filters:
            - AuthenticationFilter
        - id: stats
          uri: ${STATS} # http://localhost:8090
          predicates:
            - Path=/api/v1/stats/**
          filters:
            - AuthenticationFilter
        - id: discovery
          uri: ${DISCOVERY} # http://localhost:8761
          predicates:
            - Path=/api/v1/stats/**
          filters:
            - AuthenticationFilter
        - id: security
          uri: ${SECURITY} # http://localhost:9898
          predicates:
            - Path=/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS}
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
  application:
    name: gateway

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#DISCOVERY=http://localhost:8761;MEMBER=http://localhost:8070;PORT=8222;SECURITY=http://localhost:9898;STATS=http://localhost:8090;CORS=http://localhost:4200