eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: ${PORT}
spring:
  application:
    name: stat
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME} # postgres
    password: ${DB_PASSWORD} # root
  flyway:
    schemas: stat
    locations: classpath:db/migration
    enabled: true
    baselineOnMigrate: true
    cleanDisabled: false
    cleanOnValidationError: true
    clean-on-startup: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
